[package]
name = "meltybrain_driver_station"
version = "0.1.0"
edition = "2021"

[dependencies]
fixed = "1.28.0"
gilrs = "0.11.0"
postcard = "1.0.10"
serde = { version = "1.0.214", default-features = false }
tokio = "1.41.0"

