[package]
name = "meltybrain_driver_station"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
fixed = "1.28.0"
gilrs = "0.11.0"
itertools = "0.13.0"
postcard = "1.0.10"
serde = { version = "1.0.214", default-features = false }
tokio = { version = "1.41.0", features = ["full"] }
